class Job {
  static const List<String> job = [
    'Giáo viên',
    'Bác sĩ',
    'Kỹ sư',
    'Luật sư',
    'Nhân viên bán hàng',
    'Quản lý dự án',
    'Lập trình viên',
    'Kỹ thuật viên',
    'Nghệ sĩ',
    'Diễn viên',
    'Nhà thiết kế đồ họa',
    'Kế toán',
    'Nhân viên kinh doanh',
    'Chủ doanh nghiệp',
    'Thợ xây',
    'Thợ điện',
    'Thợ sửa ống nước',
    'Thợ sửa ô tô',
    'Thợ làm tóc',
    'Thợ làm móng',
    'Bộ đội',
    'Cảnh sát',
    'Nghệ nhân',
    'Thợ mộc',
    'Thợ hàn',
    'Thợ sửa chữa máy tính',
    'Thợ may',
    'Người mẫu',
    'Người mẹ',
    'Người bố',
    'Y tá',
    'Chăm sóc trẻ em',
    'Nha sĩ',
    'Kiến trúc sư',
    'Nhà văn',
    'Nhà báo',
    'Diễn viên hài',
    'Người mẫu ảnh',
    'Quân nhân',
    'Thợ cắt tóc',
    'Thợ chăm sóc da',
    'Biên tập viên',
    'Ca sĩ',
    'Nhạc sĩ',
    'Thợ làm bánh',
    'Phục vụ nhà hàng',
    'Công nhân xây dựng',
    'Kiểm toán viên',
    'Thợ sửa điện thoại',
    'Thợ sơn nhà',
    'Nhân viên ngân hàng',
    'Phát thanh viên',
    'Quay phim',
    'Dược sĩ',
    'Thợ săn',
    'Thợ lặn',
    'Thợ hồ',
    'Nhà sản xuất',
    'Thợ cắt may',
    'Nhà nghiên cứu',
    'Giảng viên',
    'Thủ môn',
    'Huấn luyện viên thể thao',
    'Thợ nạo vét',
    'Thợ mỏ',
    'Thợ hồ lô',
    'Thợ điện lạnh',
    'Thợ sửa chữa máy bay',
    'Thợ sửa chữa tàu thủy',
    'Bảo vệ',
    'Nhà khoa học',
    'Thợ cơ khí',
    'Thợ hồi tưởng',
    'Người bảo vệ động vật',
    'Nhân viên marketing',
    'Nhân viên quảng cáo',
    'Thợ hàn khí',
    'Thợ rèn',
    'Thợ chế tạo máy',
    'Thợ thủ công mỹ nghệ'
  ];
}
