// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbl7P-hDIv9s_eaNaL2MakCPJYLZSM-Xo',
    appId: '1:785574497303:web:d4e12de317de3e77ca2052',
    messagingSenderId: '785574497303',
    projectId: 'themedbookapp',
    authDomain: 'themedbookapp.firebaseapp.com',
    storageBucket: 'themedbookapp.appspot.com',
    measurementId: 'G-P6042638BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfqnA4Wp0wbmDQLOrjS1KW5BNPigbS1Us',
    appId: '1:785574497303:android:e1970a54eefc9d4fca2052',
    messagingSenderId: '785574497303',
    projectId: 'themedbookapp',
    storageBucket: 'themedbookapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLLsVpgzSZnRRqDxJ8hSt3vQE186YIdYg',
    appId: '1:785574497303:ios:05c249e16600b5fdca2052',
    messagingSenderId: '785574497303',
    projectId: 'themedbookapp',
    storageBucket: 'themedbookapp.appspot.com',
    iosClientId: '785574497303-7mrb9ps83qrkbb2c9j1kbr7evk962c4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.medbook',
  );
}
